name       : budgie-extras
version    : 1.5.0
release    : 16
source     :
    - https://github.com/UbuntuBudgie/budgie-extras/releases/download/v1.5.0/budgie-extras-1.5.0.tar.xz : 10d14a1f6c90d5fa8106077094f83030a5ac26cf81e9820e9c34566b182a844a
homepage   : https://github.com/UbuntuBudgie/budgie-extras
license    : GPL-3.0-or-later
component  :
    - desktop.budgie
    - ^budgie-brightness-controller-applet : desktop.budgie
    - ^budgie-countdown-applet : desktop.budgie
    - ^budgie-extras-daemon : desktop.budgie
    - ^budgie-hotcorners-applet : desktop.budgie
    - ^budgie-kangaroo-applet : desktop.budgie
    - ^budgie-previews : desktop.budgie
    - ^budgie-quicknote-applet : desktop.budgie
    - ^budgie-takeabreak-applet : desktop.budgie
    - ^budgie-visualspace-applet : desktop.budgie
    - ^budgie-weathershow-applet : desktop.budgie
    - ^budgie-window-shuffler : desktop.budgie
summary    :
    - Budgie-extras is a shared component with translations required by various applets
    - ^budgie-brightness-controller-applet : Applet to control the brightness of the screen
    - ^budgie-countdown-applet : Applet providing a countdown capability on the Budgie Desktop
    - ^budgie-extras-daemon : Extras daemon for budgie-extras capabilities
    - ^budgie-hotcorners-applet : Applet providing hotcorners capabilities for the Budgie Desktop
    - ^budgie-kangaroo-applet : Kangaroo is an applet Applet to allow quick file-browsing
    - ^budgie-previews : Provides window previews capabilities for the Budgie Desktop
    - ^budgie-quicknote-applet : Quicknote is an applet to provide the easiest possible way to make small notes
    - ^budgie-takeabreak-applet : A pomodoro like applet to prompt when to take-a-break for a set period of time
    - ^budgie-visualspace-applet : Show and manage windows in workspaces for the Budgie Desktop
    - ^budgie-weathershow-applet : Weathershow is an applet to display the weather and forecast
    - ^budgie-window-shuffler : Keyboard and GUI friendly window-tiling capability
description:
    - Budgie-extras is a shared component with translations required by various applets.
    - ^budgie-brightness-controller-applet : The brightness controller applet allows controlling of the screen levels via xrandr (fallback) or via gnome-settings-daemon (if available).
    - ^budgie-countdown-applet : A count down applet with the following options; ring a bell, flash the (panel) icon, display a message window or run a (any) command.
    - ^budgie-extras-daemon : This on logon process manages keyboard shortcuts delivered via .bde files for various extras-plugins.
    - ^budgie-hotcorners-applet : The hotcorners applet allow user defined commands to be executed when the mouse cursor is pushed into a corner of the main desktop.
    - ^budgie-kangaroo-applet : The kangaroo applet allows for quick and easy browsing, across (possibly) many directory layers, without having to do a single mouse click.
    - ^budgie-previews : Set previews to show an overview of windows in an expose like way.
    - ^budgie-quicknote-applet : The quicknote applet allows a user to record a text based note. The applet autosaves the text while writing and supports multiple undo and redo capabilities.
    - ^budgie-takeabreak-applet : Budgie TakeaBreak is a pomodoro like applet, to make sure to take regular breaks from working. Options from Budgie Settings include turning the screen upside down, dim the screen, lock screen or show a countdown message on break time. The applet can be accessed quickly from the panel to temporarily switch it off.
    - ^budgie-visualspace-applet : The visualspace applet shows as a stylish compact workspace on the budgie panel. Choosing windows in the applet popup moves to the workspace where the window is located and gives it focus. The number of Workspace can also be changed though the applet popup.
    - ^budgie-weathershow-applet : The weathershow applet displays daily and three hourly weather forecasts on both the desktop and a Popover.
    - ^budgie-window-shuffler : The window shuffler is an easy to use windows tiling capability driven primarily through the keyboard to place and move window in a grid format.
patterns   :
    - ^budgie-brightness-controller-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-brightness-controller
        - /usr/share/pixmaps/budgie-brightness-controller-1-symbolic.svg
    - ^budgie-countdown-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-countdown
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.budgie-countdown.gschema.xml
        - /usr/share/pixmaps/budgie-countdown-symbolic.svg
        - /usr/share/pixmaps/cr*
    - ^budgie-extras-daemon :
        - /usr/bin/budgie-extras-daemon
        - /usr/lib64/budgie-extras-daemon/invoke.py
        - /usr/share/budgie-desktop/layouts
        - /usr/share/budgie-extras-daemon
        - /usr/share/man/man1/budgie-extras-daemon.1
        - /usr/share/xdg/autostart/budgie-extras-daemon.desktop
    - ^budgie-hotcorners-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-hotcorners
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.budgie-hotcorners.gschema.xml
        - /usr/share/pixmaps/budgie-hotcorners-symbolic.svg
    - ^budgie-kangaroo-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-kangaroo
        - /usr/share/pixmaps/budgie-foldertrack-symbolic.svg
    - ^budgie-previews :
        - /usr/lib64/budgie-previews
        - /usr/share/applications/org.ubuntubudgie.previewscontrols.desktop
        - /usr/share/budgie-extras-daemon/preview*
        - /usr/share/icons/hicolor/scalable/apps/org.ubuntubudgie.budgiewpreviews.svg
        - /usr/share/metainfo/org.ubuntubudgie.previewscontrols.metainfo.xml
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.budgie-wpreviews.gschema.xml
        - /usr/share/pixmaps/budgie_wpreviews*
        - /usr/share/pixmaps/budgiewprviews.svg
        - /usr/share/xdg/autostart/previews*
    - ^budgie-quicknote-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-quicknote
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.quicknote.gschema.xml
        - /usr/share/pixmaps/budgie-quicknote-symbolic.svg
    - ^budgie-takeabreak-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-takeabreak
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.takeabreak.gschema.xml
        - /usr/share/pixmaps/takeabreak*
    - ^budgie-visualspace-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-visualspace
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.budgie-visualspace.gschema.xml
        - /usr/share/pixmaps/visualspace-symbolic.svg
        - /usr/share/xdg/autostart/visualspace-autostart.desktop
    - ^budgie-weathershow-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-weathershow
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.weathershow.gschema.xml
        - /usr/share/pixmaps/budgie-wticon-symbolic.svg
    - ^budgie-window-shuffler :
        - /usr/lib64/budgie-window-shuffler
        - /usr/lib64/budgie-desktop/plugins/budgie-window-shuffler/*
        - /usr/share/applications/org.ubuntubudgie.shufflercontrol.desktop
        - /usr/share/budgie-extras-daemon/windowshuffler*
        - /usr/share/glib-2.0/schemas/*shuffler*
        - /usr/share/icons/hicolor/scalable/apps/org.ubuntubudgie.shuffler-control.svg
        - /usr/share/metainfo/org.ubuntubudgie.shufflercontrol.metainfo.xml
        - /usr/share/pixmaps/shuffler*
        - /usr/share/xdg/autostart/layoutspopup-autostart.desktop
        - /usr/share/xdg/autostart/shuffler*
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(budgie-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwnck-3.0)
    - vala
rundeps    :
    - ^budgie-brightness-controller-applet : budgie-extras
    - ^budgie-countdown-applet :
        - budgie-extras
        - vorbis-tools
    - ^budgie-extras-daemon : budgie-extras
    - ^budgie-hotcorners-applet :
        - budgie-previews
        - budgie-window-shuffler
        - xdotool
    - ^budgie-kangaroo-applet : budgie-extras
    - ^budgie-previews :
        - budgie-extras-daemon
        - xinput
        - xprintidle
    - ^budgie-quicknote-applet : budgie-extras
    - ^budgie-takeabreak-applet :
        - budgie-extras
        - python-psutil
        - xprintidle
    - ^budgie-visualspace-applet : budgie-extras
    - ^budgie-weathershow-applet : budgie-extras
    - ^budgie-window-shuffler :
        - budgie-extras-daemon
        - xprop
setup      : |
    %apply_patches
    %meson_configure \
        -Dbuild-all=false \
        -Dbuild-brightness-controller=true \
        -Dbuild-countdown=true \
        -Dbuild-extrasdaemon=true \
        -Dbuild-hotcorners=true \
        -Dbuild-kangaroo=true \
        -Dbuild-quicknote=true \
        -Dbuild-takeabreak=true \
        -Dbuild-visualspace=true \
        -Dbuild-weathershow=true \
        -Dbuild-window-shuffler=true \
        -Dbuild-wpreviews=true \
        -Dxdg-appdir=/usr/share/xdg/autostart
build      : |
    %ninja_build
install    : |
    %ninja_install

