name       : budgie-extras
version    : 0.9.1
release    : 3
source     :
    - https://github.com/UbuntuBudgie/budgie-extras/releases/download/v0.9.1/budgie-extras-0.9.1.tar.xz : 20179b7eca4beddc0f7c330a9e09626b480c3704ce3271d1f34fbceb2b840bcd
license    : GPL-3.0-or-later
component  :
    - desktop.budgie
    - ^budgie-kangaroo-applet : desktop.budgie
    - ^budgie-quicknote-applet : desktop.budgie
    - ^budgie-weathershow-applet : desktop.budgie
summary    :
    - Budgie-extras is a translations file package required by various third-party applets
    - ^budgie-kangaroo-applet : Kangaroo is an applet for quick and easy browsing, across (possibly) many directory layers, without having to do a single mouse click
    - ^budgie-quicknote-applet : Quicknote is an applet to provide the easiest possible way to make small notes
    - ^budgie-weathershow-applet : Weathershow is an applet that shows the weather in the traybar, desktop icon or both
description:
    - Budgie-extras is a translations file package required by various third-party budgie applets
    - ^budgie-kangaroo-applet : Kangaroo is an applet for quick and easy browsing, across (possibly) many directory layers, without having to do a single mouse click.
    - ^budgie-quicknote-applet : Quicknote is an applet to provide the easiest possible way to make small notes. Just click the icon and write down your notes. QuickNote autosaves the text while writing,
        and comes with a ten- level undo/redo function.
    - ^budgie-weathershow-applet : Weathershow is an applet that shows the weather in the traybar, desktop icon or both.
patterns   :
    - ^budgie-kangaroo-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-kangaroo
        - /usr/share/pixmaps/budgie-foldertrack-symbolic.svg
    - ^budgie-quicknote-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-quicknote
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.quicknote.gschema.xml
        - /usr/share/pixmaps/budgie-quicknote-symbolic.svg
    - ^budgie-weathershow-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-weathershow
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.weathershow.gschema.xml
        - /usr/share/pixmaps/budgie-wticon-symbolic.svg
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
rundeps    :
    - ^budgie-kangaroo-applet : budgie-extras
    - ^budgie-quicknote-applet : budgie-extras
    - ^budgie-weathershow-applet : budgie-extras
setup      : |
    %meson_configure -Dbuild-all=false \
                     -Dbuild-kangaroo=true \
                     -Dbuild-quicknote=true \
                     -Dbuild-weathershow=true 
build      : |
    %ninja_build
install    : |
    %ninja_install
