name       : budgie-extras
version    : 1.2.0
release    : 11
source     :
    - https://github.com/UbuntuBudgie/budgie-extras/releases/download/v1.2.0/budgie-extras-1.2.0.tar.xz : fa9af5a6665c44adcacd29187dbf4810c82078b0c3aa79b8dbc121b672765733
homepage   : https://github.com/UbuntuBudgie/budgie-extras
license    : GPL-3.0-or-later
component  :
    - desktop.budgie
    - ^budgie-countdown-applet : desktop.budgie
    - ^budgie-extras-daemon : desktop.budgie
    - ^budgie-kangaroo-applet : desktop.budgie
    - ^budgie-quicknote-applet : desktop.budgie
    - ^budgie-takeabreak-applet : desktop.budgie
    - ^budgie-weathershow-applet : desktop.budgie
    - ^budgie-window-shuffler : desktop.budgie
summary    :
    - Budgie-extras is a shared component with translations required by various applets
    - ^budgie-countdown-applet : Applet providing a countdown capability on the Budgie Desktop
    - ^budgie-extras-daemon : Extras daemon for budgie-extras capabilities
    - ^budgie-kangaroo-applet : Kangaroo is an applet Applet to allow quick file-browsing
    - ^budgie-quicknote-applet : Quicknote is an applet to provide the easiest possible way to make small notes
    - ^budgie-takeabreak-applet : A pomodoro like applet to prompt when to take-a-break for a set period of time
    - ^budgie-weathershow-applet : Weathershow is an applet to display the weather and forecast
    - ^budgie-window-shuffler : Keyboard and GUI friendly window-tiling capability
description:
    - Budgie-extras is a shared component with translations required by various applets
    - ^budgie-countdown-applet : A count down applet with the following options; ring a bell, flash the (panel) icon, display a message window or run a (any) command.
    - ^budgie-extras-daemon : This on logon process manages keyboard shortcuts delivered via .bde files for various extras-plugins.
    - ^budgie-kangaroo-applet : The kangaroo applet allows for quick and easy browsing, across (possibly) many directory layers, without having to do a single mouse click.
    - ^budgie-quicknote-applet : The quicknote applet allows a user to record a text based note. The applet autosaves the text while writing and supports multiple undo and redo capabilities.
    - ^budgie-takeabreak-applet : Budgie TakeaBreak is a pomodoro like applet, to make sure to take regular breaks from working. Options from Budgie Settings include turning the screen upside down, dim the screen, lock screen or show a countdown message on break time. The applet can be accessed quickly from the panel to temporarily switch it off.
    - ^budgie-weathershow-applet : The weathershow applet displays daily and three hourly weather forecasts on both the desktop and a Popover.
    - ^budgie-window-shuffler : The window shuffler is an easy to use windows tiling capability driven primarily through the keyboard to place and move window in a grid format.
patterns   :
    - ^budgie-countdown-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-countdown
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.budgie-countdown.gschema.xml
        - /usr/share/pixmaps/budgie-countdown-symbolic.svg
        - /usr/share/pixmaps/cr*
    - ^budgie-extras-daemon :
        - /usr/bin/budgie-extras-daemon
        - /usr/lib64/budgie-extras-daemon/invoke.py
        - /usr/share/budgie-desktop/layouts
        - /usr/share/budgie-extras-daemon
        - /usr/share/man/man1/budgie-extras-daemon.1
        - /usr/share/xdg/autostart/budgie-extras-daemon.desktop
    - ^budgie-kangaroo-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-kangaroo
        - /usr/share/pixmaps/budgie-foldertrack-symbolic.svg
    - ^budgie-quicknote-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-quicknote
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.quicknote.gschema.xml
        - /usr/share/pixmaps/budgie-quicknote-symbolic.svg
    - ^budgie-takeabreak-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-takeabreak
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.takeabreak.gschema.xml
        - /usr/share/pixmaps/takeabreak*
    - ^budgie-weathershow-applet :
        - /usr/lib64/budgie-desktop/plugins/budgie-weathershow
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.plugins.weathershow.gschema.xml
        - /usr/share/pixmaps/budgie-wticon-symbolic.svg
    - ^budgie-window-shuffler :
        - /usr/lib64/budgie-window-shuffler
        - /usr/share/applications/shuffler-control.desktop
        - /usr/share/budgie-extras-daemon/windowshuffler*
        - /usr/share/glib-2.0/schemas/org.ubuntubudgie.windowshuffler.gschema.xml
        - /usr/share/pixmaps/shuffler*
        - /usr/share/xdg/autostart/layoutspopup-autostart.desktop
        - /usr/share/xdg/autostart/shuffler*
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwnck-3.0)
    - vala
rundeps    :
    - ^budgie-countdown-applet :
        - budgie-extras
        - vorbis-tools
    - ^budgie-extras-daemon : budgie-extras
    - ^budgie-kangaroo-applet : budgie-extras
    - ^budgie-quicknote-applet : budgie-extras
    - ^budgie-takeabreak-applet :
        - budgie-extras
        - python-notify2
        - python-psutil
        - xprintidle
    - ^budgie-weathershow-applet : budgie-extras
    - ^budgie-window-shuffler :
        - budgie-extras-daemon
        - xprop
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-install-dir-paths.patch
    %meson_configure --sysconfdir=/usr/share \
        -Dbuild-all=false \
        -Dbuild-countdown=true \
        -Dbuild-extrasdaemon=true \
        -Dbuild-kangaroo=true \
        -Dbuild-quicknote=true \
        -Dbuild-takeabreak=true \
        -Dbuild-weathershow=true \
        -Dbuild-window-shuffler=true
build      : |
    %ninja_build
install    : |
    %ninja_install
